manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
   
  projects:
    - name: zmk
  
      revision: main
      import: app/west.yml
  self:
    path: config
